[package]
name = "my-web-scraper"
version = "0.1.0"
authors = ["beni347"]
edition = "2021"

[dependencies]
reqwest = "0.11.13"
scraper = "0.14.0"
tokio = { version = "1", features = ["full"] }
html5ever = "0.26.0"